//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BodyFatCalculators.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BodyFatCalculators.Resources.App", typeof(App).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        public static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen (mm).
        /// </summary>
        public static string Abdomen__mm_ {
            get {
                return ResourceManager.GetString("Abdomen (mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Fat Calculator.
        /// </summary>
        public static string Body_Fat_Calculator {
            get {
                return ResourceManager.GetString("Body Fat Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest (mm).
        /// </summary>
        public static string Chest__mm_ {
            get {
                return ResourceManager.GetString("Chest (mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home?.
        /// </summary>
        public static string Go_Home_ {
            get {
                return ResourceManager.GetString("Go Home?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm).
        /// </summary>
        public static string Height__cm_ {
            get {
                return ResourceManager.GetString("Height (cm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hip (mm).
        /// </summary>
        public static string Hip__mm_ {
            get {
                return ResourceManager.GetString("Hip (mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hips (cm).
        /// </summary>
        public static string Hips__cm_ {
            get {
                return ResourceManager.GetString("Hips (cm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caliper (3 Site).
        /// </summary>
        public static string JacksonAndPollock3SiteSkinFold {
            get {
                return ResourceManager.GetString("JacksonAndPollock3SiteSkinFold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naval (cm).
        /// </summary>
        public static string Naval__cm_ {
            get {
                return ResourceManager.GetString("Naval (cm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck (cm).
        /// </summary>
        public static string Neck__cm_ {
            get {
                return ResourceManager.GetString("Neck (cm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address....
        /// </summary>
        public static string Sorry__there_s_nothing_at_this_address___ {
            get {
                return ResourceManager.GetString("Sorry, there\'s nothing at this address...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thigh (mm).
        /// </summary>
        public static string Thigh__mm_ {
            get {
                return ResourceManager.GetString("Thigh (mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricep (mm).
        /// </summary>
        public static string Tricep__mm_ {
            get {
                return ResourceManager.GetString("Tricep (mm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US Navy.
        /// </summary>
        public static string USNavy {
            get {
                return ResourceManager.GetString("USNavy", resourceCulture);
            }
        }
    }
}
